Continue image refresh if /etc/nodepool exists
My image already has a /etc/nodepool which causes the bootstrapServer to
fails with:

  Exception: Unable to make config dir
  command: sudo mkdir /etc/nodepool

project-config seems to create it as well:

 $ tail -n2 nodepool/elements/nodepool-base/finalise.d/99-nodepool-dir
 mkdir /etc/nodepool
 chmod 0777 /etc/nodepool

But apparently the OS instance is not impacted.

Use `mkdir -p`, to ignore a directory already existing.

Change-Id: I7caf3f366a97211da50aa83d49c7b10ac00458b3